### ISSUE TITLE
Ethcontract integration

### ISSUE THREAD

**Issue by e00E** [gnosis/oba-services#46]
For our end2end demo we are going to want to call smart contracts through ethcontract like in dex-services. In dex-services we have the `conctracts` workspace crate for this.
I feel that for this crate it would be better to copy paste it here because we might have special requirements that don't apply to dex-services (where we haven't had to touch it in a long time) and so that we don't have to do the work of making it more standalone as it currenlty hardcodes the contracts that are needed. Eventually it would still be nice to do this but it is going to be more efficient later when we know exactly what we need for oba-services.
@nlordell @fleupold what do you think?

**Comment by nlordell** [comment]
I think it's fine to copy-paste

**Comment by fleupold** [comment]
I'm also fine with copy pasting. 
In this project, I think the integration of and interaction with external smart contracts will play a much larger role than in dex-services and I'm not sure we can use the npm module approach for all projects (e.g. the GasToken is not vendored via npm), therefore I think we might have to adjust this solution anyways going forward.
